-- =============================================
-- Supabase 테이블 생성 SQL
-- Supabase 대시보드 → SQL Editor에 붙여넣고 실행하세요
-- =============================================

create table submissions (
  id             bigint generated by default as identity primary key,
  submitted_at   timestamptz default now(),

  -- 기본 정보
  group_type     text,           -- 'single' or 'multi'
  class_num      text,
  group_num      text,
  members        jsonb,          -- [{studentId, name}, ...]

  -- 1차시
  s1_field       text,
  s1_sdg         text,
  s1_title       text,
  s1_summary     text,
  s1_regional_link text,
  s1_subjects    jsonb,          -- ['과목1', '과목2']
  s1_reason      text,
  s1_problem     text,
  s1_writer_id   text,
  s1_writer_name text,

  -- 2차시
  s2_cases       text,
  s2_policies    text,
  s2_links       jsonb,          -- ['링크1', '링크2']
  s2_writer_id   text,
  s2_writer_name text,

  -- 3-4차시
  s3_solution    text,
  s3_links       jsonb,
  s3_writer_id   text,
  s3_writer_name text,

  -- 5-6차시
  s5_plan        text,
  s5_tool        text,
  s5_description text,
  s5_roles       jsonb,          -- [{name, role}, ...]
  s5_writer_id   text,
  s5_writer_name text
);

-- =============================================
-- RLS(Row Level Security) 설정
-- 누구나 insert 가능, 읽기는 막음 (선생님만 대시보드에서 확인)
-- =============================================
alter table submissions enable row level security;

create policy "누구나 제출 가능"
  on submissions for insert
  to anon
  with check (true);

-- 선생님 계정(authenticated)만 조회 가능
create policy "인증된 사용자만 조회"
  on submissions for select
  to authenticated
  using (true);
